.github/workflows/nodejs.yml
Add client ci action for linting and testing.
=> Add nodejs.yml

.github/workflows/elixir.yml
Add github action for running unit tests on pushes to master and pull requests.
=> Add elixir.yml

docker-compose.yml, server/Dockerfile, server/growbud/config/dev.exs
Add DockerFile for setting up the server and database.
Requires docker and docker-compose. Run docker-compose up to get going.
#13 
#15
=> Add docker files for running server locally

server/Dockerfile
In order to watch for file changes and reload the server code
we need inotify tools to be installed.
=> Install inotify-tools

.github/workflows/elixir.yml
The action should look for changes in the server directory.
=> Fix look for changes in the server directory

docker-compose.yml
In order to create the tables we need to also run ecto migrate :walking_man: :smiley: :baby_chick:
=> Fix non existing tables error

client/Dockerfile, client/package-lock.json, client/package.json, client/src/views/Home.vue, docker-compose.yml, package-lock.json
Add hotreload for Vue in local dev docker container
=> add hotreload for Vue in local docker container

docker-compose.yml
Configure where docker-compose can find the server code. This
will enable hot reloading of the app during development.
=> Add volume definition for server

documentation/types.gql
Let's get the discussion going :running_man:
=> Describe types with the Graphql type system

server/data-store/package-lock.json, server/data-store/package.json
=> Bump to typescript 3.7

.github/workflows/data-store-ci.yml
Let's make sure i write decent code XD
=> Add ci for data-store

server/data-store/src/lib/auth/index.ts, server/data-store/src/schema/index.ts
Let's also return the userId such that we may later use it when creating schedules etc.
=> Return userId on register and login

.github/PULL_REQUEST_TEMPLATE.md
Lets start using a template for PRs
=> Add PR_TEMPLATE

client/firebase.json
Added firebase.json to project so we can deploy with github actions
This will be tested when it is merged and hopefully firebase action can deploy.
=> Add firebase.json to fix deploy issue

client/public/index.html
*Description*
Change title of app in index.html to match app name of Growbud
*How to test?*
Start dev and check title of app on tab
=> Change title of app in index.html

server/data-store/package.json, server/data-store/tsconfig.json
*Description*
ESNEXT wasn't a good target. ?? operator seems to fail for some reason.
In some commit i must have moved the index.js file. Update start script
to execute it and not thin air.
*How to test?*
npm run tsc-build && npm start. The project should compile and serve localhost:9090
=> Update typescript target and start script

server/data-store/src/lib/db/index.ts, server/data-store/src/schema/index.ts
*Description*
Allow a schedule interval argument to be set and retrieved.
*How to test?*
Make wateringSchedule queries and mutations with interval and observe it's presence.
=> Add interval argument to watering schdule

server/data-store/src/index.ts
*Description*
Add a simple log of requests made to the server.
*How to test?*
Make any request and note it in the server logs
=> Add simple request logging

client/.gitignore, client/package-lock.json, client/package.json, client/src/api/auth/index.js, client/src/components/LoggedinToolbar.vue, client/src/components/LoggedoutToolbar.vue, client/src/components/LoginModal.vue, client/src/layouts/Default.vue, client/src/main.js, client/src/store.js
*Description*
The app can now store JWT sent from login and can also call the backend for a silentRefresh of JWT so a user can stay logged in.
*How to test?*
Build the docker container and test the login functionality.
Lower the time for the refresh to take place to test the functionality of the refresh function.
Go to src/main.js and decrease the interval time for 
```
window.setInterval(function () { store.dispatch('silentTokenRefresh'); }, 360000);
```
=> Add jwt to vuex store on login

.github/workflows/client-deploy.yml
*Description*
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
*How to test?*
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
=> update firebase workflow

.github/PULL_REQUEST_TEMPLATE.md
This looks better?
Don't you agree?
=> Change headers to better reflect that they are headers

client/src/components/IncrementerButton.vue, client/src/router.js, client/src/views/AddWateringSchedule.vue
All components needed for the addWateringSchedule are in this PR. They have no events bound to them yet.
Pull this branch and run the docker container. 
Check that the all the UI components are there. Reference the figma design.
=> Add components for wateringschedule

.github/workflows/client-deploy.yml
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
=> Global install of firebase-tools

client/firebase.json
Change upload folder to dist since production builds are placed there.
Do a local deploy from the client folder.
=> Change which folder should be uploaded to firebase

client/src/components/LoggedinToolbar.vue, client/src/router.js, client/src/views/MyWateringSchedules.vue
Added navbar for **AddWateringSchedule** and **MyWateringSchedules**
Build project
log in
click the navbar buttons in the top right.
=> Add navbar for loggedin user

server/data-store/src/index.ts
Only show graphiql if env is development
change node_env to anything else and it won't show.
=> Only show graphiql of env is development

server/data-store/src/lib/auth/index.ts
Refactor refreshToken to use no intermediate variables and capture expires to milliseconds in own function. 
Login then refresh token.
=> Refactor refreshToken function

server/data-store/src/lib/auth/index.ts
Refactor login function to remove local state variables and use
expires to milliseconds function.
Login in a user should work as before.
=> Refactor login function

client/src/router.js, client/src/store.js, client/src/views/MyWateringSchedules.vue
When refreshing the webpage a blank html page was shown and a second refresh was needed to show content. **vue/vue-router** needed to be configured to look for the correct variables before reload. This was done by calling the correct [router guard](https://router.vuejs.org/guide/advanced/navigation-guards.html#in-component-guards)
Login and reload the page. Check that all components load and render on the page.
=> Fix displaying blank page when refreshing webpage

server/data-store/package-lock.json, server/data-store/package.json
Make the commit process interactive to improve the quality of the commit messages and add a change log
N/A
=> feat: make data-store commitizen friendly

.github/workflows/trigger-schedules.yml
Add a cron job that will trigger the function for notifying users its
time to water their plants every 12h.
Merge and see if it works -\(''/)/-
=> feat: 🎸 Trigger watering schedules notifications

.github/workflows/node-audit.yml
Since most of our javascript code runs on node 10 it's prudent to check
for updates there as well I think.. maybe.
N/A
=> ci: 🎡 Check node v10 in npm audit

server/data-store/src/schema/index.ts
Change the documentation of interval from unix timestamp to int to
reflect how the value is acctually used.
N/A
=> docs: ✏️ Update documentation for interval

server/data-store/src/lib/pushNotifcationToken/index.ts, server/data-store/src/schema/index.ts
A user should be able to register devices that should receive push notifications. 
1 create a user,
2 register a device token, note in db,
3 register token for another device.
4 update token in step 2 and note changes, token in step 3 should be unaffected.
=> register push notification token

client/src/App.vue, client/src/views/AddWateringSchedule.vue, client/src/views/MyWateringSchedules.vue
A snackbar is shown in bottom left corner when you add or update a watering schedule.
Add and update a schedule.
Then check for the snackbar in bottom left
=> Add snackbar notification on schedule mutation

client/src/components/TimePicker.vue
When adding a time in addWateringSchedule view the timepicker will scroll the chosen hour and minute into view when clicking it for added convenience for the user.
Test the timepicker when adding a new schedule and updating a schedule
=> Add scrollIntoView for the chosen time in timepicker

client/src/scss/globals.scss, client/src/scss/variables.scss, client/src/views/AddWateringSchedule.vue, client/vue.config.js
Contains validation for Wateringschedule + change of the layout. Design isn't responsive yet.
Build project and try to enter a date and time before current timepoint.
Try to send a wateringschedule when no plants or time/date is given.
=> Add validation to wateringSchedule

.github/workflows/client-deploy.yml
Deploy to master site on successful merge.
N/A
=> ci: deploy to master on merge

client/.firebaserc
By adding aliases to firebase we may push to the correct environment depending on the context. (master branch, production branch, local dev).
firbase use <alias> to switch.
=> ci: 🎡 Add firebase environment aliases

client/src/registerServiceWorker.js, client/src/sw.js, client/vue.config.js
The service worker has been updated to handle offline caching. Google lighthouse gives green check marks but further configuration is needed. This is just for further development
Run google lighthouse on live site
=> feat: 🎸 add sw for offline caching

server/data-store/src/index.ts
TypeError: Converting circular structure to JSON thrown in the refreshToken Route
Deploy
=> fix(index): circular stringify error

server/data-store/src/lib/auth/index.ts, server/data-store/src/schema/index.ts
We should handle errors better
Deploy
=> fix(error handling): catch token decode errors

client/vue.config.js
Change the name of the app from client to Growbud.
Push to default env and load the app in a chrome/brave browser
=> feat: 🎸 update client pwa name, start_url and display

client/src/api/notifications/index.js, client/src/components/LoginModal.vue, client/src/main.js, server/data-store/src/index.ts, server/data-store/src/lib/auth/index.ts, server/data-store/src/lib/http/index.ts, server/data-store/src/schema/index.ts
Post a device token to the backend when firebase returns it.
=> feat: 🎸 Register device token on messaging getToken

client/src/components/LoginModal.vue
You can now login by pressing enter
✅ Closes: #113
=> feat: 🎸 login on enter

client/public/firebase-messaging-sw.js
Replace boilerplate values with whats actually sent with the notification.
Users should be notified what action should be taken when a background notification triggers.
* Be logged in to the app
* Have another tab in focus
* send a push notification from the commandline gcloud pubsub topics publish send-push-notifications --message '{"userId":"xxxx", "payload": {"title": "xxx", "body":"xxx" }}' 
=> feat: 🎸 display title and text sent from notification

client/public/index.html, client/src/App.vue, client/src/components/LoggedinToolbar.vue, client/src/components/LoggedoutToolbar.vue, client/src/scss/variables.scss, client/src/views/AddWateringSchedule.vue
New color schemed for the app, Going for green theme with a gradient
going from warm to cold tone
Gradients are a big thing in 2020 and it seems to be considered a modern design. Also consult https://lawsofux.com/ rule #5 Jakobs Law. 
"Users spend most of their time on other sites. This means that users prefer your site to work the same way as all the other sites they already know."
Build a local project and comment and provide feedback on how you think the colors look
<List any dependencies …
=> feat: 🎸 Fancy new color scheme suited for 2020 (Gradients Rule)

client/src/App.vue, client/src/components/IncrementerButton.vue, client/src/components/LoggedinToolbar.vue, client/src/components/LoggedoutToolbar.vue, client/src/components/TimePicker.vue, client/src/scss/globals.scss, client/src/scss/variables.scss, client/src/views/AddWateringSchedule.vue
redesign addwateringschedule view as mobile first
This is the first version. I have focused on the layout and color scheme. This will be the basis of further iterations. I have only created a design for viewports 600px and less
Go to add wateringschedules and verify that you can access all features
=> style: 💄 redesign addwateringschedule view as mobile first

client/src/components/AuthButtonsAndModals.vue
Missied this styling in previous pr
=> style: 💄 Adding missing styling for authbuttons

client/public/index.html, client/src/components/AuthButtonsAndModals.vue, client/src/components/LoginModal.vue, client/src/components/MyWateringScheduleCard.vue, client/src/components/SignupModal.vue, client/src/components/TimePicker.vue, client/src/components/Toolbar.vue, client/src/scss/globals.scss, client/src/scss/variables.scss, client/src/views/AddWateringSchedule.vue, server/data-store/growbud-developer.app.yaml
This is the first attempt at mobile first design for auth modals. I have changed the appearance of primary buttons. Im feel like a style is developing that I like. Please give feedback on the design.
Test to login and sign up.
Please comment on how the experience felt :)
=> feat: 🎸 first mobile desing of auth modals v1

.github/workflows/data-store-deploy.yml, server/data-store/example.app.yaml
We try to deploy with a non existing file resulting in errors.
=> fix: 🐛 Deploy to data-store on merge

client/src/api/auth/index.js, client/src/components/LoginModal.vue, client/src/components/Toolbar.vue, client/src/main.js, client/src/router.js, client/src/scss/globals.scss, client/src/views/Profile.vue
A profile view is now accessible by clicking the icon in top right
corner. You can press a button to re request permission from the Notifications API
With this I also had to update the vue-router to not allow entering urls if you arent logged in
This gives the user an opportunity to chose when notifications should happen. This feature needs to be set per device
I blocked notifications -> go to profile -> press the button to allow notifications -> then answer question from Notifications API
<List …
=> feat: 🎸 Add profile view with allownotifications button

client/src/components/LoginModal.vue, client/src/components/SignupModal.vue, client/src/components/Toolbar.vue, client/src/scss/globals.scss, client/src/scss/variables.scss
This PR will reudce the heavy usage of dark colors that I felt was to
cluttering. The new design is a compromise between older version. I
still retain gradients and color usage but using more white. This
because I feel it gives the app a more modern look.
The design will most likely keep changing and evolve as I learn more.
Build locally and check out the new design. Leave comments on what you think.
=> feat: 🎸 Reduce heavy usage of dark color

.github/workflows/data-store-ci.yml
run ci job on node 10 since that's whats used in production.
=> chore: 🤖 run ci job node 10

server/data-store/package-lock.json, server/functions/package-lock.json, server/notifications/package-lock.json
Track all package-lock.json files in the server sub directories.
=> chore: 🤖 track server package-lock.json files

.github/workflows/client-deploy.yml, .github/workflows/data-store-ci.yml, .github/workflows/data-store-deploy.yml, install-client.sh, install-server.sh, server/data-store/example.app.yaml, server/data-store/package-lock.json, server/data-store/package.json, server/functions/package-lock.json, server/notifications/package-lock.json
=> ci: 🎡 deploy client to firebase with token

client/src/components/AuthButtonsAndModals.vue, client/src/components/IncrementerButton.vue, client/src/components/MyWateringScheduleCard.vue, client/src/components/Toolbar.vue, client/src/scss/globals.scss, client/src/scss/variables.scss, client/src/views/AddWateringSchedule.vue, client/src/views/MyWateringSchedules.vue
Most buttons have a new hover effect and has been aligned to the color
theme.
The hover effects are smoother now which will hopefully make it more pleasant to use the ui.
This is only grahpical changes in this PR
Check that the buttons hover effect is to your liking. Not all buttons have a hover effect thou.
=> feat: 🎸 Align behaviour and color of buttons in the app

server/data-store/src/deviceTokens/route.ts, server/data-store/src/logging/index.ts
=> refactor: make logging functional
