Kalk88/GrowBud

README.md
Added instructions for installing docker and docker compose to help
new comers get started. Docker compose allows for easy setup of a dev
environment and in the future we can use it for end to end testing.
=> Add instructions to run locally in readme

server/growbud/lib/growbud/accounts.ex, server/growbud/lib/growbud/accounts/credential.ex, server/growbud/lib/growbud/accounts/registration.ex, server/growbud/priv/repo/migrations/20191001191659_create_credentials.exs
Due to how changesets where handled the user credentials
were not stored. It slipped through since email pass could be null.
=> Fix credentials not stored

.github/workflows/node-audit.yml
Run npm audit on our node folders once a week.  This will make keeping our dependencies up to date more likely and more maintainable.
No testing performed.
=> Add npm audit workflow

.github/workflows/client-deploy.yml
*Description*
As per documentation https://github.com/marketplace/actions/github-action-for-firebase
PROJECT_PATH must be added as env if firebase.json is not in root and i dont think it is in root of repo since its under /client/firebase.json
*How to test?*
MERGE AND PRAY
=> Add PROJECT_PATH env to firebase deploy job

server/data-store/Dockerfile, server/data-store/package.json, server/data-store/tsconfig.json
*Description*
During the setup npm install would fail because of two reasons:
- One the src folder couldn't be found.
- Two google cloud doesn't support node 12 and the libraries were not
installed properly.
*How to test?*
docker-compose up --build
go to [graphiql](http://localhost:9090/graph/view)
=> Fix data-store installation procedure

.github/workflows/data-store-deploy.yml
*Description*
Updated the deploy action, we should build the project before pushing to google cloud else
it can't find the dist folder.
*How to test?*
Test next time we merge a feature to master.
=> Fix data-store deploy

server/data-store/src/lib/auth/index.ts, server/data-store/src/schema/index.ts
*Description*
Return a refresh token on registration and login. This is needed if we want to keep tokens alive without the user to have to login again.
*How to test?*
Spin up the server and test write a mutation in graphqil like the one below.
mutation{
login(email:"e@mail", password:"somepw") {
JWT,
id,
refreshToken
}
}
=> Add Refreshtoken

docker-compose.yml
*Description*
remove "volumes:" from docker-compose.yml to fix issue with typescript dist build being overwritten by local files.
*How to test?*
Run docker-compose up --build and check that server fires up
=> remove volumes: to fix server build step

server/data-store/src/lib/db/index.ts, server/data-store/src/schema/index.ts
*Description*
A user should be able to remove a schedule. This pr introduces a function to remove a schedule by Id.
*How to test?*
1. Create a schedule and not the Id
2. Remove it  by calling removeWateringScheduleById with the Id from previous request.
=> Add function for removing watering schedule

server/data-store/package-lock.json, server/data-store/package.json, server/data-store/src/index.ts, server/data-store/src/lib/auth/index.ts
*Description*
The client can't extract a value from a HTTP only cookie thus the endpoint could never receive the refresh token. Now we parse the cookie sent by the client instead.
*How to test?*
1. Login as a user to receive refresh token cookie.
2. Make a refresh request and note the new token.
=> Fix refreshroute not parsing cookie

server/data-store/src/lib/auth/index.ts, server/data-store/src/schema/index.ts
Call the login function explicitly after registering the user. It's easier to reason about if the function calls aren't nested.
Register a user and you should receive a JWT and refresh token cookie as normal.
=> Refactor registration flow

server/data-store/src/index.ts
White list which domains may call the api of environment is set to
development. Also enable Access-Control-Allow-Credentials such that
tokens may be refreshed.
You should be able to login on the web client after docker-compose up
=> White list development domains and allow creds

server/data-store/app.yaml, server/data-store/src/.env.example, server/data-store/src/index.ts
Read whitelist from process.env, for local dev it's set in the .env file for prod in app.yml
Docker-compose up --build. Should work as normal for dev. For prod firebase and gcp needs to be deployd from commandline.
=> Update where whitelist config is read from

client/package-lock.json, client/package.json, client/src/vue.config.js
These changes brings forth the godly and heavenly splendor of [scss](https://sass-lang.com/documentation/syntax) support for css styling.
I love it.
Check that package.json contains sass-loader and sass
"sass": "^1.24.2",
"sass-loader": "^8.0.0",
And check that the vue.config.js contains webpack config for using scss.
=> Add support for sass/scss

server/data-store/src/lib/db/index.ts, server/data-store/src/schema/index.ts
Add graphql mutation for updating existing schedule.
Create a new schedule with:
mutation {
nextWateringDateFor(plants: [{name:"p1"}, {name:"asdd"}],userId:"hh", timestamp: "123", interval: 2333) {
id,
plants {
name
}
}
}
and update with:
mutation {
updateWateringSchedule(scheduleId:"Id", plants: [{name:"plant"}],userId:"hh", timestamp: "123", interval: 2333) {
id,
plants {
name
}
}
}
=> Add graphql mutation for updating existing schedule.

client/src/router.js
There was a bug preventing vue router to access /addWateringSchedule and /myWateringSchedules.
The wrong variable was checked for routing
Build project login and go to either myWateringSchedules or addWateringSchedule
=> Change variable that checks if routing is allowed

client/src/api/wateringschedule/index.js, client/src/views/AddWateringSchedule.vue, client/src/views/MyWateringSchedules.vue, server/data-store/src/schema/index.ts
userId is no more an argument to schedule functions. Instead we take the userId from the JWT and use that instead.
Login in and create a schedule, view the list of schedules and update the one you created.
=> Remove userId from gql functions

server/data-store/app.yaml, server/data-store/src/index.ts
The origin header may only contain one value so we have to match it with the white list.
Add different origins to the whitelist e.g http://localhost:8080 to the .env white list and try make requests with the client from those origins, against the backend.
=> Fix access control allow origin header

server/data-store/src/lib/wateringSchedules/index.ts, server/data-store/src/schema/index.ts
Schedule would be read twice on fetch due to the offset always being
set.
Check number of retrieves made in dev console before fetching schedules. Should not be twice the amount of fetched schedules after a get.
=> Fix watering schedule double read

client/src/api/wateringschedule/index.js, client/src/views/AddWateringSchedule.vue
A button for removing schedules has been added. It is only visible when
trying to update an existing schedule.
This enables the user to remove unwanted schedules from the UI
I added a new wateringschedule. Went to my wateringschedules and clicked the card.
This brought me to the updatewateringschedule view which displays the remove schedule button.
Clicking it removes the schedule from my wateringschedules view (Due to a update error you have to refresh the my watering schedules view to see the changes)
Create watering schedule
Click the card in my watering …
=> feat: 🎸 add remove schedule button in updatewateringschedule vy

server/cloud-functions/functions/package.json, server/cloud-functions/functions/src/index.ts, server/cloud-functions/functions/tsconfig.json
Send push notifications to registered devices when we find schedules that should be notified.
When a user has set a watering schedule they expect to be notified within a certain time every given interval. 
* Login on the client and enable notifications, to register a token, you might have to login again . Set a schedule for a plant.
* run:  gcloud pubsub topics publish send-push-notifications --message '{"userId":"xxxx",  "payload": {"title": "xxx", "body":"xxx" }}' to send a message.
<List any …
=> feat: push schedule notice

server/data-store/Dockerfile
Express-helpers.ts didnt get copied to docker container in dockerfile
for server.
This PR adds the COPY command for the missing file in the dockerfile for server
I ran docker-compose up --build and was able to build the project and login as test user
Run docker-compose up --build and check if the project builds
=> fix: 🐛 Missing module that didnt get copied to docker container

client/src/main.js, client/src/store.js, client/src/views/AddWateringSchedule.vue, client/src/views/MyWateringSchedules.vue
We had a bug were the Client couldn't fetch data from backend because the fetch was sent before the store had the JWT.
Before each router navigation we check for the JWT and we wait for the response before we let the user continue with navigation.
Login -> go to myWateringSchedules and verify that the schedules are loaded even when refreshing.
Test the following and make sure the UI updates in between each action: 
-Add new schedule 
-Update schedule 
-Delete schedule 
<List any dependencies …
=> fix: 🐛 Wait till store is initialized before calling graphql

server/data-store/package.json
@types dependencies are only for development.
Run install.sh and firebase_serve.sh, dataStore should  still be accessible.
=> chore: 🤖 Move types dependencies for some libs to dev deps
